### ISSUE TITLE
TODO!!

### ISSUE THREAD

**Issue by qandrew** [qandrew/evernote-analysis#1]
## Preprocessing

- [ ] format html files to have lines and tabs accordingly
- [ ] convert to markdown

## Features

- [ ] total word count
